baseURL = 'https://rizqi.colte.dev/'
languageCode = 'id-id'
defaultContentLanguage = 'id-id'
title = 'Rizqi'
theme = 'hermit'
rssLimit = 10
pluralizeListTitles = false
enableEmoji = true
timeZone = 'Asia/Jakarta'
disqusShortname = 'mrizqirmdhn'

[author]
  name = 'Muhammad Rizqi Ramadhan'

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  homeSubtitle = 'Saya Muhammad Rizqi Ramadhan, ini adalah tempat untuk menampung semua tulisan kurang jelas saya'
  # footerCopyright = ' &#183 <a href="https://instagram.com/mrizqirmdhn_">R</a>'

[[params.social]]
  name = 'instagram'
  url = 'https://instagram.com/mrizqirmdhn_'

[[params.social]]
  name = 'github'
  url = 'https://github.com/ZefianAlfian'

[menu]
  [[menu.main]]
    name = 'Tulisan'
    url = 'tulisan/'
    weight = 10

  [[menu.main]]
    name = 'About'
    url = 'about-rizqi/'
    weight = 20

    # Comment config
[params.page.comment]
  enable = true
  # Disqus comment config (https://disqus.com/)
  [params.page.comment.disqus]
    enable = true
    # Disqus shortname to use Disqus in posts
    shortname = "mrizqirmdhn"
